/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmStatus: typeof import('./src/components/AlarmStatus.vue')['default']
    EditAlarm: typeof import('./src/components/EditAlarm.vue')['default']
    QRCode: typeof import('./src/components/QRCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
    TestRequest: typeof import('./src/components/TestRequest.vue')['default']
    TimeZone: typeof import('./src/components/TimeZone.vue')['default']
  }
}
